services:
  mysql:
    image: mysql:8.0
    container_name: memory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: memory_db
      MYSQL_USER: memory_user
      MYSQL_PASSWORD: memory_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build: .
    container_name: memory-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/memory_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: memory_user
      SPRING_DATASOURCE_PASSWORD: memory_password
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: dummy_access_key
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: dummy_secret_key
      CLOUD_AWS_REGION_STATIC: ap-northeast-2
      CLOUD_AWS_S3_BUCKET: dummy_bucket
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: memory-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  mysql_data: 