package zim.tave.memory.service;

import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import zim.tave.memory.domain.Country;
import zim.tave.memory.repository.CountryRepository;

import java.util.List;

@Service
@Transactional
@RequiredArgsConstructor
public class CountryService {

    private final CountryRepository countryRepository;



    public List<Country> searchCountriesByName(String keyword) {
        return countryRepository.findByNameContaining(keyword);
    }

    public Country findByCode(String countryCode) {
        return countryRepository.findByCode(countryCode);
    }

    public void saveCountry(Country country) {
        countryRepository.save(country);
    }

    public void init() {
        if (!countryRepository.findAll().isEmpty()) return;

        List<Country> countries = List.of(
                new Country("KR", "대한민국", "🇰🇷"),
                new Country("US", "미국", "🇺🇸"),
                new Country("JP", "일본", "🇯🇵"),
                new Country("CN", "중국", "🇨🇳"),
                new Country("FR", "프랑스", "🇫🇷"),
                new Country("DE", "독일", "🇩🇪"),
                new Country("GB", "영국", "🇬🇧"),
                new Country("IT", "이탈리아", "🇮🇹"),
                new Country("ES", "스페인", "🇪🇸"),
                new Country("CA", "캐나다", "🇨🇦")
//                new Country("AW", "Aruba", "🇦🇼"),
//                new Country("AF", "Afghanistan", "🇦🇫"),
//                new Country("AO", "Angola", "🇦🇴"),
//                new Country("AI", "Anguilla", "🇦🇮"),
//                new Country("AX", "Åland Islands", "🇦🇽"),
//                new Country("AL", "Albania", "🇦🇱"),
//                new Country("AD", "Andorra", "🇦🇩"),
//                new Country("AE", "United Arab Emirates", "🇦🇪"),
//                new Country("AR", "아르헨티나", "🇦🇷"),
//                new Country("AM", "Armenia", "🇦🇲"),
//                new Country("AS", "American Samoa", "🇦🇸"),
//                new Country("AQ", "Antarctica", "🇦🇶"),
//                new Country("TF", "French Southern Territories", "🇹🇫"),
//                new Country("AG", "Antigua and Barbuda", "🇦🇬"),
//                new Country("AU", "호주", "🇦🇺"),
//                new Country("AT", "Austria", "🇦🇹"),
//                new Country("AZ", "Azerbaijan", "🇦🇿"),
//                new Country("BI", "Burundi", "🇧🇮"),
//                new Country("BE", "벨기에", "🇧🇪"),
//                new Country("BJ", "Benin", "🇧🇯"),
//                new Country("BQ", "Bonaire, Sint Eustatius and Saba", "🇧🇶"),
//                new Country("BF", "Burkina Faso", "🇧🇫"),
//                new Country("BD", "Bangladesh", "🇧🇩"),
//                new Country("BG", "Bulgaria", "🇧🇬"),
//                new Country("BH", "Bahrain", "🇧🇭"),
//                new Country("BS", "Bahamas", "🇧🇸"),
//                new Country("BA", "Bosnia and Herzegovina", "🇧🇦"),
//                new Country("BL", "Saint Barthélemy", "🇧🇱"),
//                new Country("BY", "Belarus", "🇧🇾"),
//                new Country("BZ", "Belize", "🇧🇿"),
//                new Country("BM", "Bermuda", "🇧🇲"),
//                new Country("BO", "Bolivia, Plurinational State of", "🇧🇴"),
//                new Country("BR", "브라질", "🇧🇷"),
//                new Country("BB", "Barbados", "🇧🇧"),
//                new Country("BN", "Brunei Darussalam", "🇧🇳"),
//                new Country("BT", "Bhutan", "🇧🇹"),
//                new Country("BV", "Bouvet Island", "🇧🇻"),
//                new Country("BW", "Botswana", "🇧🇼"),
//                new Country("CF", "Central African Republic", "🇨🇫"),
//                new Country("CA", "캐나다", "🇨🇦"),
//                new Country("CC", "Cocos (Keeling) Islands", "🇨🇨"),
//                new Country("CH", "스위스", "🇨🇭"),
//                new Country("CL", "Chile", "🇨🇱"),
//                new Country("CN", "중국", "🇨🇳"),
//                new Country("CI", "Côte d'Ivoire", "🇨🇮"),
//                new Country("CM", "Cameroon", "🇨🇲"),
//                new Country("CD", "Congo, The Democratic Republic of the", "🇨🇩"),
//                new Country("CG", "Congo", "🇨🇬"),
//                new Country("CK", "Cook Islands", "🇨🇰"),
//                new Country("CO", "Colombia", "🇨🇴"),
//                new Country("KM", "Comoros", "🇰🇲"),
//                new Country("CV", "Cabo Verde", "🇨🇻"),
//                new Country("CR", "Costa Rica", "🇨🇷"),
//                new Country("CU", "Cuba", "🇨🇺"),
//                new Country("CW", "Curaçao", "🇨🇼"),
//                new Country("CX", "Christmas Island", "🇨🇽"),
//                new Country("KY", "Cayman Islands", "🇰🇾"),
//                new Country("CY", "Cyprus", "🇨🇾"),
//                new Country("CZ", "체코", "🇨🇿"),
//                new Country("DE", "독일", "🇩🇪"),
//                new Country("DJ", "Djibouti", "🇩🇯"),
//                new Country("DM", "Dominica", "🇩🇲"),
//                new Country("DK", "덴마크", "🇩🇰"),
//                new Country("DO", "Dominican Republic", "🇩🇴"),
//                new Country("DZ", "Algeria", "🇩🇿"),
//                new Country("EC", "Ecuador", "🇪🇨"),
//                new Country("EG", "Egypt", "🇪🇬"),
//                new Country("ER", "Eritrea", "🇪🇷"),
//                new Country("EH", "Western Sahara", "🇪🇭"),
//                new Country("ES", "스페인", "🇪🇸"),
//                new Country("EE", "Estonia", "🇪🇪"),
//                new Country("ET", "Ethiopia", "🇪🇹"),
//                new Country("FI", "핀란드", "🇫🇮"),
//                new Country("FJ", "Fiji", "🇫🇯"),
//                new Country("FK", "Falkland Islands (Malvinas)", "🇫🇰"),
//                new Country("FR", "프랑스", "🇫🇷"),
//                new Country("FO", "Faroe Islands", "🇫🇴"),
//                new Country("FM", "Micronesia, Federated States of", "🇫🇲"),
//                new Country("GA", "Gabon", "🇬🇦"),
//                new Country("GB", "영국", "🇬🇧"),
//                new Country("GE", "Georgia", "🇬🇪"),
//                new Country("GG", "Guernsey", "🇬🇬"),
//                new Country("GH", "Ghana", "🇬🇭"),
//                new Country("GI", "Gibraltar", "🇬🇮"),
//                new Country("GN", "Guinea", "🇬🇳"),
//                new Country("GP", "Guadeloupe", "🇬🇵"),
//                new Country("GM", "Gambia", "🇬🇲"),
//                new Country("GW", "Guinea-Bissau", "🇬🇼"),
//                new Country("GQ", "Equatorial Guinea", "🇬🇶"),
//                new Country("GR", "그리스", "🇬🇷"),
//                new Country("GD", "Grenada", "🇬🇩"),
//                new Country("GL", "Greenland", "🇬🇱"),
//                new Country("GT", "Guatemala", "🇬🇹"),
//                new Country("GF", "French Guiana", "🇬🇫"),
//                new Country("GU", "Guam", "🇬🇺"),
//                new Country("GY", "Guyana", "🇬🇾"),
//                new Country("HK", "Hong Kong", "🇭🇰"),
//                new Country("HM", "Heard Island and McDonald Islands", "🇭🇲"),
//                new Country("HN", "Honduras", "🇭🇳"),
//                new Country("HR", "Croatia", "🇭🇷"),
//                new Country("HT", "Haiti", "🇭🇹"),
//                new Country("HU", "헝가리", "🇭🇺"),
//                new Country("ID", "Indonesia", "🇮🇩"),
//                new Country("IM", "Isle of Man", "🇮🇲"),
//                new Country("IN", "인도", "🇮🇳"),
//                new Country("IO", "British Indian Ocean Territory", "🇮🇴"),
//                new Country("IE", "Ireland", "🇮🇪"),
//                new Country("IR", "Iran, Islamic Republic of", "🇮🇷"),
//                new Country("IQ", "Iraq", "🇮🇶"),
//                new Country("IS", "Iceland", "🇮🇸"),
//                new Country("IL", "Israel", "🇮🇱"),
//                new Country("IT", "이탈리아", "🇮🇹"),
//                new Country("JM", "Jamaica", "🇯🇲"),
//                new Country("JE", "Jersey", "🇯🇪"),
//                new Country("JO", "Jordan", "🇯🇴"),
//                new Country("JP", "일본", "🇯🇵"),
//                new Country("KZ", "Kazakhstan", "🇰🇿"),
//                new Country("KE", "Kenya", "🇰🇪"),
//                new Country("KG", "Kyrgyzstan", "🇰🇬"),
//                new Country("KH", "Cambodia", "🇰🇭"),
//                new Country("KI", "Kiribati", "🇰🇮"),
//                new Country("KN", "Saint Kitts and Nevis", "🇰🇳"),
//                new Country("KR", "대한민국", "🇰🇷"),
//                new Country("KW", "Kuwait", "🇰🇼"),
//                new Country("LA", "Lao People's Democratic Republic", "🇱🇦"),
//                new Country("LB", "Lebanon", "🇱🇧"),
//                new Country("LR", "Liberia", "🇱🇷"),
//                new Country("LY", "Libya", "🇱🇾"),
//                new Country("LC", "Saint Lucia", "🇱🇨"),
//                new Country("LI", "Liechtenstein", "🇱🇮"),
//                new Country("LK", "Sri Lanka", "🇱🇰"),
//                new Country("LS", "Lesotho", "🇱🇸"),
//                new Country("LT", "Lithuania", "🇱🇹"),
//                new Country("LU", "Luxembourg", "🇱🇺"),
//                new Country("LV", "Latvia", "🇱🇻"),
//                new Country("MO", "Macao", "🇲🇴"),
//                new Country("MF", "Saint Martin (French part)", "🇲🇫"),
//                new Country("MA", "Morocco", "🇲🇦"),
//                new Country("MC", "Monaco", "🇲🇨"),
//                new Country("MD", "Moldova, Republic of", "🇲🇩"),
//                new Country("MG", "Madagascar", "🇲🇬"),
//                new Country("MV", "Maldives", "🇲🇻"),
//                new Country("MX", "멕시코", "🇲🇽"),
//                new Country("MH", "Marshall Islands", "🇲🇭"),
//                new Country("MK", "North Macedonia", "🇲🇰"),
//                new Country("ML", "Mali", "🇲🇱"),
//                new Country("MT", "Malta", "🇲🇹"),
//                new Country("MM", "Myanmar", "🇲🇲"),
//                new Country("ME", "Montenegro", "🇲🇪"),
//                new Country("MN", "Mongolia", "🇲🇳"),
//                new Country("MP", "Northern Mariana Islands", "🇲🇵"),
//                new Country("MZ", "Mozambique", "🇲🇿"),
//                new Country("MR", "Mauritania", "🇲🇷"),
//                new Country("MS", "Montserrat", "🇲🇸"),
//                new Country("MQ", "Martinique", "🇲🇶"),
//                new Country("MU", "Mauritius", "🇲🇺"),
//                new Country("MW", "Malawi", "🇲🇼"),
//                new Country("MY", "Malaysia", "🇲🇾"),
//                new Country("YT", "Mayotte", "🇾🇹"),
//                new Country("NA", "Namibia", "🇳🇦"),
//                new Country("NC", "New Caledonia", "🇳🇨"),
//                new Country("NE", "Niger", "🇳🇪"),
//                new Country("NF", "Norfolk Island", "🇳🇫"),
//                new Country("NG", "Nigeria", "🇳🇬"),
//                new Country("NI", "Nicaragua", "🇳🇮"),
//                new Country("NU", "Niue", "🇳🇺"),
//                new Country("NL", "네덜란드", "🇳🇱"),
//                new Country("NO", "노르웨이", "🇳🇴"),
//                new Country("NP", "Nepal", "🇳🇵"),
//                new Country("NR", "Nauru", "🇳🇷"),
//                new Country("NZ", "뉴질랜드", "🇳🇿"),
//                new Country("OM", "Oman", "🇴🇲"),
//                new Country("PK", "Pakistan", "🇵🇰"),
//                new Country("PA", "Panama", "🇵🇦"),
//                new Country("PN", "Pitcairn", "🇵🇳"),
//                new Country("PE", "Peru", "🇵🇪"),
//                new Country("PH", "Philippines", "🇵🇭"),
//                new Country("PW", "Palau", "🇵🇼"),
//                new Country("PG", "Papua New Guinea", "🇵🇬"),
//                new Country("PL", "폴란드", "🇵🇱"),
//                new Country("PR", "Puerto Rico", "🇵🇷"),
//                new Country("KP", "Korea, Democratic People's Republic of", "🇰🇵"),
//                new Country("PT", "Portugal", "🇵🇹"),
//                new Country("PY", "Paraguay", "🇵🇾"),
//                new Country("PS", "Palestine, State of", "🇵🇸"),
//                new Country("PF", "French Polynesia", "🇵🇫"),
//                new Country("QA", "Qatar", "🇶🇦"),
//                new Country("RE", "Réunion", "🇷🇪"),
//                new Country("RO", "Romania", "🇷🇴"),
//                new Country("RU", "러시아", "🇷🇺"),
//                new Country("RW", "Rwanda", "🇷🇼"),
//                new Country("SA", "Saudi Arabia", "🇸🇦"),
//                new Country("SD", "Sudan", "🇸🇩"),
//                new Country("SN", "Senegal", "🇸🇳"),
//                new Country("SG", "Singapore", "🇸🇬"),
//                new Country("GS", "South Georgia and the South Sandwich Islands", "🇬🇸"),
//                new Country("SH", "Saint Helena, Ascension and Tristan da Cunha", "🇸🇭"),
//                new Country("SJ", "Svalbard and Jan Mayen", "🇸🇯"),
//                new Country("SB", "Solomon Islands", "🇸🇧"),
//                new Country("SL", "Sierra Leone", "🇸🇱"),
//                new Country("SV", "El Salvador", "🇸🇻"),
//                new Country("SM", "San Marino", "🇸🇲"),
//                new Country("SO", "Somalia", "🇸🇴"),
//                new Country("PM", "Saint Pierre and Miquelon", "🇵🇲"),
//                new Country("RS", "Serbia", "🇷🇸"),
//                new Country("SS", "South Sudan", "🇸🇸"),
//                new Country("ST", "Sao Tome and Principe", "🇸🇹"),
//                new Country("SR", "Suriname", "🇸🇷"),
//                new Country("SK", "Slovakia", "🇸🇰"),
//                new Country("SI", "Slovenia", "🇸🇮"),
//                new Country("SE", "스웨덴", "🇸🇪"),
//                new Country("SZ", "Eswatini", "🇸🇿"),
//                new Country("SX", "Sint Maarten (Dutch part)", "🇸🇽"),
//                new Country("SC", "Seychelles", "🇸🇨"),
//                new Country("SY", "Syrian Arab Republic", "🇸🇾"),
//                new Country("TC", "Turks and Caicos Islands", "🇹🇨"),
//                new Country("TD", "Chad", "🇹🇩"),
//                new Country("TG", "Togo", "🇹🇬"),
//                new Country("TH", "Thailand", "🇹🇭"),
//                new Country("TJ", "Tajikistan", "🇹🇯"),
//                new Country("TK", "Tokelau", "🇹🇰"),
//                new Country("TM", "Turkmenistan", "🇹🇲"),
//                new Country("TL", "Timor-Leste", "🇹🇱"),
//                new Country("TO", "Tonga", "🇹🇴"),
//                new Country("TT", "Trinidad and Tobago", "🇹🇹"),
//                new Country("TN", "Tunisia", "🇹🇳"),
//                new Country("TR", "터키", "🇹🇷"),
//                new Country("TV", "Tuvalu", "🇹🇻"),
//                new Country("TW", "Taiwan, Province of China", "🇹🇼"),
//                new Country("TZ", "Tanzania, United Republic of", "🇹🇿"),
//                new Country("UG", "Uganda", "🇺🇬"),
//                new Country("UA", "Ukraine", "🇺🇦"),
//                new Country("UM", "United States Minor Outlying Islands", "🇺🇲"),
//                new Country("UY", "Uruguay", "🇺🇾"),
//                new Country("US", "미국", "🇺🇸"),
//                new Country("UZ", "Uzbekistan", "🇺🇿"),
//                new Country("VA", "Holy See (Vatican City State)", "🇻🇦"),
//                new Country("VC", "Saint Vincent and the Grenadines", "🇻🇨"),
//                new Country("VE", "Venezuela, Bolivarian Republic of", "🇻🇪"),
//                new Country("VG", "Virgin Islands, British", "🇻🇬"),
//                new Country("VI", "Virgin Islands, U.S.", "🇻🇮"),
//                new Country("VN", "Viet Nam", "🇻🇳"),
//                new Country("VU", "Vanuatu", "🇻🇺"),
//                new Country("WF", "Wallis and Futuna", "🇼🇫"),
//                new Country("WS", "Samoa", "🇼🇸"),
//                new Country("YE", "Yemen", "🇾🇪"),
//                new Country("ZA", "남아프리카공화국", "🇿🇦"),
//                new Country("ZM", "Zambia", "🇿🇲"),
//                new Country("ZW", "Zimbabwe", "🇿🇼")
        );
    }
}
